on:
  push:
    branches:
      - dev
jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: install pnpm globally
              run: npm install -g pnpm


            - name: Install dependencies
              run: pnpm i

            - name: Run tests
              run: pnpm format

            - name: Run build
              run: pnpm build